### ISSUE TITLE
Editor crashes when Post edit block selected with other blocks 

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/sb-post-edit-block#2]
When I was attempting Call #7: Polished portfolios I experienced the Editor crashing.

I documented this at https://sneak-peek.me/2021/06/11/call-7-polished-portfolios/

The problem occurs when the Post Edit block is selected as part of multiple block selection.

3 blocks selected
![image](https://user-images.githubusercontent.com/2474435/121789534-bc6e9f80-cbce-11eb-935f-436c0c402f1d.png)

Attempting to select the Post Edit block leads to
![image](https://user-images.githubusercontent.com/2474435/121789548-d9a36e00-cbce-11eb-9550-76e281aeb99d.png)

The error is
```
TypeError: Cannot read property 'lastChild' of null
    at np (https://sneak-peek.me/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=88d0ba7a6e6f356fbb72073b72436b2a:81:22824)
    at https://sneak-peek.me/wp-content/plugins/gutenberg/build/block-editor/index.js?ver=88d0ba7a6e6f356fbb72073b72436b2a:81:23828
    at Bh (https://sneak-peek.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:126:456)
    at Dj (https://sneak-peek.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:162:476)
    at unstable_runWithPriority (https://sneak-peek.me/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25:260)
    at Da (https://sneak-peek.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:60:280)
    at xb (https://sneak-peek.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:162:231)
    at Te (https://sneak-peek.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:146:79)
    at https://sneak-peek.me/wp-content/plugins/gutenberg/vendor/react-dom.min.de439aae.js:61:68
    at unstable_runWithPriority (https://sneak-peek.me/wp-content/plugins/gutenberg/vendor/react.min.e713ea3b.js:25:260)
```

Note: The Post edit block is almost impossible to select in the block editor anyway.
So something needs to be changed. Maybe whatever's necessary to make the block selectable will solve the problem.
Perhaps just allowing the user to define the `(Edit)` string will be enough.

**Comment by bobbingwide** [comment]
### Proposed solution

- [x] Allow the `(Edit)` label for the link to. Be editable.
- [x] Add block supports values similar to the Post Date block: align, typography
- [x] Eliminate Server Side Rendering code when in the editor. Can the save method be removed completely?
- [x] Update SSR to support label and alignment settings.

**Comment by bobbingwide** [comment]
In this screen capture, the 3 blocks selected are:
1. The group block containing featured image, title and post date
2. The Post edit block
3. The spacer that follows

The Post edit block is styled with align center, link colour white and background black.
 
![image](https://user-images.githubusercontent.com/2474435/121850458-b539b580-cce4-11eb-8ad9-dbbb45c9c269.png)

**Comment by bobbingwide** [comment]
This is now fixed in v0.1.0. 
Need to upload to sneak-peek.me and test.

**Comment by bobbingwide** [comment]
I haven't uploaded the block to sneak-peek.me. It now appears that the block doesn't work in s.b/wp55/thisis
I don't yet have a clue why not.

**Comment by bobbingwide** [comment]
> I haven't uploaded the block to sneak-peek.me. It now appears that the block doesn't work in s.b/wp55/thisis
I don't yet have a clue why not.

I belive the problem is explained by my investigation in https://github.com/bobbingwide/thisis/issues/34

### Proposed solution

Apply the workaround suggested, and retest in `s.b/wp55/thisis` and sneak-peek.me

**Comment by bobbingwide** [comment]
> Apply the workaround suggested, and retest in s.b/wp55/thisis

I retested in `https://s.b/wp55/thisis/2021/06/13/post-edit-block/`, logged in and out, with and without the workaround.

**Comment by bobbingwide** [comment]
I retested in https://sneak-peek.me/2021/06/13/post-edit-block/
After noting that the casual visitor won't actually see the link I updated the post to include the screenshot for the plugin.
